import "./globals.css";
import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";

const atkinson_hyperlegible = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={atkinson_hyperlegible.className}>{children}</body>
    </html>
  );
}
